In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\jpinf\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\jpinf\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\jpinf\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The pgf.debug rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.

In [2]:
train = pd.read_csv('crop_yield.csv')

In [3]:
train

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,cat_crop,soil_type
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.00,Nuts,Laterite or red or alluvial
1,Andaman and Nicobar Islands,NICOBARS,2001,Kharif,Arecanut,1254.0,2061.00,Nuts,Laterite or red or alluvial
2,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Arecanut,1258.0,2083.00,Nuts,Laterite or red or alluvial
3,Andaman and Nicobar Islands,NICOBARS,2003,Whole Year,Arecanut,1261.0,1525.00,Nuts,Laterite or red or alluvial
4,Andaman and Nicobar Islands,NICOBARS,2004,Whole Year,Arecanut,1264.7,805.85,Nuts,Laterite or red or alluvial
...,...,...,...,...,...,...,...,...,...
94370,West Bengal,PURULIA,2004,Whole Year,Turmeric,270.0,166.00,Species,Alluvial or Black
94371,West Bengal,PURULIA,2005,Whole Year,Turmeric,284.0,229.00,Species,Alluvial or Black
94372,West Bengal,PURULIA,2006,Whole Year,Turmeric,294.0,261.00,Species,Alluvial or Black
94373,West Bengal,PURULIA,2007,Whole Year,Turmeric,289.0,178.00,Species,Alluvial or Black
94374,West Bengal,PURULIA,2008,Whole Year,Turmeric,289.0,378.00,Species,Alluvial or Black

In [4]:
train['State_Name'].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Assam', 'Goa',
       'Karnataka', 'Kerala', 'Meghalaya', 'Puducherry', 'Tamil Nadu',
       'West Bengal', 'Bihar', 'Chhattisgarh', 'Dadra and Nagar Haveli',
       'Gujarat', 'Haryana', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Rajasthan', 'Telangana ', 'Uttar Pradesh', 'Arunachal Pradesh',
       'Himachal Pradesh', 'Jammu and Kashmir ', 'Nagaland', 'Odisha',
       'Uttarakhand', 'Mizoram', 'Punjab', 'Tripura', 'Chandigarh',
       'Jharkhand', 'Sikkim'], dtype=object)

In [5]:
train['District_Name'].unique()

array(['NICOBARS', 'NORTH AND MIDDLE ANDAMAN', 'SOUTH ANDAMANS',
       'ANANTAPUR', 'EAST GODAVARI', 'KRISHNA', 'VIZIANAGARAM',
       'WEST GODAVARI', 'BAKSA', 'BARPETA', 'BONGAIGAON', 'CACHAR',
       'CHIRANG', 'DARRANG', 'DHEMAJI', 'DHUBRI', 'DIBRUGARH',
       'DIMA HASAO', 'GOALPARA', 'GOLAGHAT', 'HAILAKANDI', 'JORHAT',
       'KAMRUP', 'KAMRUP METRO', 'KARBI ANGLONG', 'KARIMGANJ',
       'KOKRAJHAR', 'LAKHIMPUR', 'MARIGAON', 'NAGAON', 'NALBARI',
       'SIVASAGAR', 'SONITPUR', 'TINSUKIA', 'UDALGURI', 'NORTH GOA',
       'SOUTH GOA', 'BAGALKOT', 'BANGALORE RURAL', 'BELGAUM', 'BELLARY',
       'BENGALURU URBAN', 'CHAMARAJANAGAR', 'CHIKBALLAPUR', 'CHIKMAGALUR',
       'CHITRADURGA', 'DAKSHIN KANNAD', 'DAVANGERE', 'DHARWAD', 'GADAG',
       'HASSAN', 'HAVERI', 'KODAGU', 'KOLAR', 'MANDYA', 'MYSORE',
       'RAMANAGARA', 'SHIMOGA', 'TUMKUR', 'UDUPI', 'UTTAR KANNAD',
       'ALAPPUZHA', 'ERNAKULAM', 'IDUKKI', 'KANNUR', 'KASARAGOD',
       'KOLLAM', 'KOTTAYAM', 'KOZHIKODE', 'MALAPPURAM', 'PALAKKAD',
       'PATHANAMTHITTA', 'THIRUVANANTHAPURAM', 'THRISSUR', 'WAYANAD',
       'EAST GARO HILLS', 'EAST JAINTIA HILLS', 'EAST KHASI HILLS',
       'NORTH GARO HILLS', 'RI BHOI', 'SOUTH GARO HILLS',
       'SOUTH WEST GARO HILLS', 'SOUTH WEST KHASI HILLS',
       'WEST GARO HILLS', 'WEST JAINTIA HILLS', 'WEST KHASI HILLS',
       'MAHE', 'COIMBATORE', 'CUDDALORE', 'DHARMAPURI', 'DINDIGUL',
       'ERODE', 'KANNIYAKUMARI', 'KARUR', 'KRISHNAGIRI', 'MADURAI',
       'NAGAPATTINAM', 'NAMAKKAL', 'PERAMBALUR', 'PUDUKKOTTAI', 'SALEM',
       'THANJAVUR', 'THE NILGIRIS', 'THENI', 'THIRUVARUR',
       'TIRUCHIRAPPALLI', 'TIRUNELVELI', 'TIRUPPUR', 'TIRUVANNAMALAI',
       'VELLORE', 'VILLUPURAM', 'VIRUDHUNAGAR', '24 PARAGANAS NORTH',
       '24 PARAGANAS SOUTH', 'BANKURA', 'BARDHAMAN', 'BIRBHUM',
       'COOCHBEHAR', 'DARJEELING', 'DINAJPUR DAKSHIN', 'DINAJPUR UTTAR',
       'HOOGHLY', 'HOWRAH', 'JALPAIGURI', 'MALDAH', 'MEDINIPUR EAST',
       'MEDINIPUR WEST', 'MURSHIDABAD', 'NADIA', 'PURULIA', 'CHITTOOR',
       'GUNTUR', 'KADAPA', 'KURNOOL', 'PRAKASAM', 'SPSR NELLORE',
       'SRIKAKULAM', 'VISAKHAPATANAM', 'ARARIA', 'ARWAL', 'BEGUSARAI',
       'BHAGALPUR', 'DARBHANGA', 'GAYA', 'GOPALGANJ', 'KAIMUR (BHABUA)',
       'KATIHAR', 'KHAGARIA', 'KISHANGANJ', 'MADHEPURA', 'MADHUBANI',
       'MUZAFFARPUR', 'NAWADA', 'PASHCHIM CHAMPARAN', 'PURBI CHAMPARAN',
       'PURNIA', 'SAHARSA', 'SAMASTIPUR', 'SARAN', 'SHEOHAR', 'SITAMARHI',
       'SIWAN', 'SUPAUL', 'VAISHALI', 'BALOD', 'BALODA BAZAR',
       'BALRAMPUR', 'BASTAR', 'BEMETARA', 'BIJAPUR', 'BILASPUR',
       'DANTEWADA', 'DHAMTARI', 'DURG', 'GARIYABAND', 'JANJGIR-CHAMPA',
       'JASHPUR', 'KABIRDHAM', 'KANKER', 'KONDAGAON', 'KORBA', 'KOREA',
       'MAHASAMUND', 'MUNGELI', 'NARAYANPUR', 'RAIGARH', 'RAIPUR',
       'RAJNANDGAON', 'SUKMA', 'SURGUJA', 'DADRA AND NAGAR HAVELI',
       'AHMADABAD', 'AMRELI', 'ANAND', 'BHARUCH', 'BHAVNAGAR', 'DANG',
       'GANDHINAGAR', 'JUNAGADH', 'KACHCHH', 'KHEDA', 'NARMADA',
       'NAVSARI', 'PANCH MAHALS', 'SABAR KANTHA', 'SURAT', 'TAPI',
       'VADODARA', 'VALSAD', 'FARIDABAD', 'JHAJJAR', 'KURUKSHETRA',
       'PANIPAT', 'SONIPAT', 'BIDAR', 'GULBARGA', 'KOPPAL', 'RAICHUR',
       'ANUPPUR', 'BALAGHAT', 'BARWANI', 'BETUL', 'BURHANPUR',
       'CHHATARPUR', 'CHHINDWARA', 'DAMOH', 'DEWAS', 'DHAR', 'HARDA',
       'HOSHANGABAD', 'JHABUA', 'KATNI', 'KHANDWA', 'KHARGONE',
       'MANDSAUR', 'PANNA', 'RAISEN', 'RAJGARH', 'RATLAM', 'REWA',
       'SAGAR', 'SATNA', 'SEHORE', 'SEONI', 'SHAHDOL', 'SHIVPURI',
       'SIDHI', 'SINGRAULI', 'TIKAMGARH', 'UJJAIN', 'UMARIA',
       'AHMEDNAGAR', 'AKOLA', 'AMRAVATI', 'AURANGABAD', 'BEED',
       'BHANDARA', 'BULDHANA', 'DHULE', 'HINGOLI', 'JALGAON', 'JALNA',
       'KOLHAPUR', 'LATUR', 'NANDED', 'NANDURBAR', 'OSMANABAD',
       'PARBHANI', 'PUNE', 'RAIGAD', 'RATNAGIRI', 'SANGLI', 'SATARA',
       'SINDHUDURG', 'SOLAPUR', 'THANE', 'WARDHA', 'WASHIM', 'YAVATMAL',
       'BISHNUPUR', 'CHANDEL', 'CHURACHANDPUR', 'IMPHAL EAST',
       'IMPHAL WEST', 'SENAPATI', 'TAMENGLONG', 'THOUBAL', 'UKHRUL',
       'KARAIKAL', 'PONDICHERRY', 'YANAM', 'ALWAR', 'BANSWARA', 'PALI',
       'RAJSAMAND', 'ARIYALUR', 'KANCHIPURAM', 'RAMANATHAPURAM',
       'SIVAGANGA', 'THIRUVALLUR', 'TUTICORIN', 'ADILABAD', 'KARIMNAGAR',
       'KHAMMAM', 'MAHBUBNAGAR', 'MEDAK', 'NALGONDA', 'NIZAMABAD',
       'RANGAREDDI', 'WARANGAL', 'ALIGARH', 'ALLAHABAD', 'AMBEDKAR NAGAR',
       'AMETHI', 'AURAIYA', 'AZAMGARH', 'BAGHPAT', 'BAHRAICH', 'BALLIA',
       'BARABANKI', 'BAREILLY', 'BASTI', 'BUDAUN', 'BULANDSHAHR',
       'DEORIA', 'ETAH', 'FAIZABAD', 'FARRUKHABAD', 'FATEHPUR',
       'GHAZIABAD', 'GONDA', 'GORAKHPUR', 'HARDOI', 'HATHRAS', 'JALAUN',
       'JAUNPUR', 'KANNAUJ', 'KANPUR DEHAT', 'KAUSHAMBI', 'KHERI',
       'KUSHI NAGAR', 'LUCKNOW', 'MAHARAJGANJ', 'MAINPURI', 'MATHURA',
       'MAU', 'MIRZAPUR', 'MORADABAD', 'MUZAFFARNAGAR', 'PILIBHIT',
       'PRATAPGARH', 'RAE BARELI', 'RAMPUR', 'SAMBHAL',
       'SANT KABEER NAGAR', 'SHAHJAHANPUR', 'SHRAVASTI',
       'SIDDHARTH NAGAR', 'SITAPUR', 'SULTANPUR', 'UNNAO', 'ANJAW',
       'CHANGLANG', 'DIBANG VALLEY', 'EAST KAMENG', 'EAST SIANG',
       'KURUNG KUMEY', 'LOHIT', 'LONGDING', 'LOWER DIBANG VALLEY',
       'LOWER SUBANSIRI', 'PAPUM PARE', 'TAWANG', 'TIRAP', 'UPPER SIANG',
       'UPPER SUBANSIRI', 'WEST KAMENG', 'WEST SIANG', 'BANKA', 'BHOJPUR',
       'BUXAR', 'JEHANABAD', 'LAKHISARAI', 'MUNGER', 'NALANDA', 'PATNA',
       'ROHTAS', 'SURAJPUR', 'BANAS KANTHA', 'DOHAD', 'JAMNAGAR',
       'MAHESANA', 'PATAN', 'RAJKOT', 'SURENDRANAGAR', 'AMBALA',
       'BHIWANI', 'FATEHABAD', 'GURGAON', 'HISAR', 'JIND', 'KAITHAL',
       'KARNAL', 'MAHENDRAGARH', 'MEWAT', 'PANCHKULA', 'REWARI', 'ROHTAK',
       'SIRSA', 'YAMUNANAGAR', 'CHAMBA', 'HAMIRPUR', 'KANGRA', 'KULLU',
       'MANDI', 'SHIMLA', 'SIRMAUR', 'SOLAN', 'UNA', 'ANANTNAG', 'BADGAM',
       'BARAMULLA', 'JAMMU', 'KATHUA', 'KULGAM', 'POONCH', 'PULWAMA',
       'RAJAURI', 'SRINAGAR', 'UDHAMPUR', 'YADGIR', 'AGAR MALWA',
       'ALIRAJPUR', 'ASHOKNAGAR', 'BHIND', 'BHOPAL', 'DATIA', 'DINDORI',
       'GUNA', 'GWALIOR', 'INDORE', 'JABALPUR', 'MANDLA', 'MORENA',
       'NARSINGHPUR', 'NEEMUCH', 'SHAJAPUR', 'SHEOPUR', 'VIDISHA',
       'DIMAPUR', 'KIPHIRE', 'KOHIMA', 'LONGLENG', 'MOKOKCHUNG', 'MON',
       'PEREN', 'PHEK', 'TUENSANG', 'WOKHA', 'ZUNHEBOTO', 'ANUGUL',
       'BALANGIR', 'BALESHWAR', 'BARGARH', 'BHADRAK', 'BOUDH', 'CUTTACK',
       'DEOGARH', 'DHENKANAL', 'GAJAPATI', 'GANJAM', 'JAGATSINGHAPUR',
       'JAJAPUR', 'JHARSUGUDA', 'KALAHANDI', 'KANDHAMAL', 'KENDRAPARA',
       'KENDUJHAR', 'KHORDHA', 'KORAPUT', 'MALKANGIRI', 'MAYURBHANJ',
       'NABARANGPUR', 'NAYAGARH', 'NUAPADA', 'PURI', 'RAYAGADA',
       'SAMBALPUR', 'SONEPUR', 'SUNDARGARH', 'AJMER', 'BARAN', 'BARMER',
       'BHARATPUR', 'BHILWARA', 'BIKANER', 'BUNDI', 'CHITTORGARH',
       'CHURU', 'DAUSA', 'DHOLPUR', 'DUNGARPUR', 'GANGANAGAR',
       'HANUMANGARH', 'JAIPUR', 'JAISALMER', 'JALORE', 'JHALAWAR',
       'JHUNJHUNU', 'JODHPUR', 'KARAULI', 'KOTA', 'NAGAUR',
       'SAWAI MADHOPUR', 'SIKAR', 'SIROHI', 'TONK', 'UDAIPUR',
       'HYDERABAD', 'AGRA', 'AMROHA', 'BANDA', 'BIJNOR', 'CHANDAULI',
       'CHITRAKOOT', 'ETAWAH', 'FIROZABAD', 'GAUTAM BUDDHA NAGAR',
       'GHAZIPUR', 'HAPUR', 'JHANSI', 'KANPUR NAGAR', 'KASGANJ',
       'LALITPUR', 'MAHOBA', 'MEERUT', 'SAHARANPUR', 'SANT RAVIDAS NAGAR',
       'SHAMLI', 'SONBHADRA', 'VARANASI', 'ALMORA', 'BAGESHWAR',
       'CHAMOLI', 'CHAMPAWAT', 'DEHRADUN', 'HARIDWAR', 'NAINITAL',
       'PAURI GARHWAL', 'PITHORAGARH', 'RUDRA PRAYAG', 'TEHRI GARHWAL',
       'UTTAR KASHI', 'AIZAWL', 'LUNGLEI', 'PORBANDAR', 'PALWAL',
       'KINNAUR', 'SAMBA', 'CHANDRAPUR', 'GADCHIROLI', 'NAGPUR', 'NASHIK',
       'CHAMPHAI', 'KOLASIB', 'LAWNGTLAI', 'MAMIT', 'SAIHA', 'AMRITSAR',
       'BARNALA', 'BATHINDA', 'FARIDKOT', 'FAZILKA', 'FIROZEPUR',
       'JALANDHAR', 'LUDHIANA', 'MANSA', 'MOGA', 'MUKTSAR', 'PATIALA',
       'SANGRUR', 'TARN TARAN', 'DHALAI', 'GOMATI', 'KHOWAI',
       'NORTH TRIPURA', 'SEPAHIJALA', 'SOUTH TRIPURA', 'UNAKOTI',
       'WEST TRIPURA', 'REASI', 'UDAM SINGH NAGAR', 'SHEIKHPURA',
       'GONDIA', 'PALGHAR', 'HOSHIARPUR', 'RUPNAGAR', 'JAMUI',
       'CHANDIGARH', 'LAHUL AND SPITI', 'BANDIPORA', 'DODA', 'GANDERBAL',
       'KARGIL', 'KISHTWAR', 'KUPWARA', 'RAMBAN', 'SHOPIAN', 'BOKARO',
       'CHATRA', 'DEOGHAR', 'DHANBAD', 'DUMKA', 'EAST SINGHBUM', 'GARHWA',
       'GIRIDIH', 'GODDA', 'GUMLA', 'HAZARIBAGH', 'JAMTARA', 'KODERMA',
       'LATEHAR', 'LOHARDAGA', 'PAKUR', 'PALAMU', 'RANCHI', 'SAHEBGANJ',
       'SARAIKELA KHARSAWAN', 'SIMDEGA', 'WEST SINGHBHUM', 'MUMBAI',
       'SERCHHIP', 'FATEHGARH SAHIB', 'GURDASPUR', 'KAPURTHALA',
       'NAWANSHAHR', 'PATHANKOT', 'S.A.S NAGAR', 'EAST DISTRICT',
       'NORTH DISTRICT', 'SOUTH DISTRICT', 'WEST DISTRICT', 'LEH LADAKH',
       'KHUNTI', 'RAMGARH'], dtype=object)

In [6]:
train['Crop_Year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2006, 2010, 2005, 2008, 2009, 2011,
       2012, 2013, 2007, 1997, 1998, 1999, 2014, 2015], dtype=int64)

In [7]:
train['Season'].unique()

array(['Kharif     ', 'Whole Year ', 'Rabi       ', 'Winter     ',
       'Autumn     ', 'Summer     '], dtype=object)

In [8]:
train['soil_type'].unique()

array([' Laterite or red or alluvial', 'Clayey or Latterite',
       ' loamy or sandy or Clayey', 'sandy ', 'Black or Red or Loamy',
       'sandy or red or lateritic  or Clayey', 'Clayey or sandy', 'Sandy',
       'Alluvial or Black', 'Clayey or Alluvial or Black', 'Clayey',
       'Sandy or Black', 'Clayey or Alluvial', 'Loamy or Black',
       'Black or Red'], dtype=object)

In [9]:
train.loc[train['Crop']=='Arecanut', 'Crop'] = 0
train.loc[train['Crop']=='Banana', 'Crop'] =1
train.loc[train['Crop']=='Dry chillies', 'Crop'] =2
train.loc[train['Crop']=='Coconut ', 'Crop'] = 3
train.loc[train['Crop']=='Cotton(lint)', 'Crop'] =4
train.loc[train['Crop']=='Dry ginger', 'Crop'] = 5
train.loc[train['Crop']=='Groundnut', 'Crop'] =6
train.loc[train['Crop']=='Maize', 'Crop'] = 7
train.loc[train['Crop']=='Moong(Green Gram)', 'Crop'] =8
train.loc[train['Crop']=='Onion', 'Crop'] = 9
train.loc[train['Crop']=='Paddy', 'Crop'] =10
train.loc[train['Crop']=='Ragi', 'Crop'] =11
train.loc[train['Crop']=='Sugarcane', 'Crop'] =12
train.loc[train['Crop']=='Tobacco', 'Crop'] =13
train.loc[train['Crop']=='Turmeric', 'Crop'] =14
train.loc[train['Crop']=='Rice', 'Crop'] =15

In [10]:
train

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,cat_crop,soil_type
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,0,1254.0,2000.00,Nuts,Laterite or red or alluvial
1,Andaman and Nicobar Islands,NICOBARS,2001,Kharif,0,1254.0,2061.00,Nuts,Laterite or red or alluvial
2,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,0,1258.0,2083.00,Nuts,Laterite or red or alluvial
3,Andaman and Nicobar Islands,NICOBARS,2003,Whole Year,0,1261.0,1525.00,Nuts,Laterite or red or alluvial
4,Andaman and Nicobar Islands,NICOBARS,2004,Whole Year,0,1264.7,805.85,Nuts,Laterite or red or alluvial
...,...,...,...,...,...,...,...,...,...
94370,West Bengal,PURULIA,2004,Whole Year,14,270.0,166.00,Species,Alluvial or Black
94371,West Bengal,PURULIA,2005,Whole Year,14,284.0,229.00,Species,Alluvial or Black
94372,West Bengal,PURULIA,2006,Whole Year,14,294.0,261.00,Species,Alluvial or Black
94373,West Bengal,PURULIA,2007,Whole Year,14,289.0,178.00,Species,Alluvial or Black
94374,West Bengal,PURULIA,2008,Whole Year,14,289.0,378.00,Species,Alluvial or Black

In [11]:
train.loc[train['soil_type']==' Laterite or red or alluvial', 'soil_type'] = 0
train.loc[train['soil_type']=='Clayey or Latterite', 'soil_type'] =1
train.loc[train['soil_type']==' loamy or sandy or Clayey', 'soil_type'] =2
train.loc[train['soil_type']=='sandy ', 'soil_type'] = 3
train.loc[train['soil_type']=='Black or Red or Loamy', 'soil_type'] =4
train.loc[train['soil_type']=='sandy or red or lateritic  or Clayey', 'soil_type'] = 5
train.loc[train['soil_type']=='Clayey or sandy', 'soil_type'] =6
train.loc[train['soil_type']=='Sandy', 'soil_type'] = 7
train.loc[train['soil_type']=='Alluvial or Black', 'soil_type'] =8
train.loc[train['soil_type']=='Clayey or Alluvial or Black', 'soil_type'] = 9
train.loc[train['soil_type']=='Clayey', 'soil_type'] =10
train.loc[train['soil_type']=='Sandy or Black', 'soil_type'] =11
train.loc[train['soil_type']=='Clayey or Alluvial', 'soil_type'] =12
train.loc[train['soil_type']=='Loamy or Black', 'soil_type'] =13
train.loc[train['soil_type']=='Black or Red', 'soil_type'] =14

In [12]:
X=train[["soil_type","Area"]]
y=train["Crop"]

In [15]:
y

0         0
1         0
2         0
3         0
4         0
         ..
94370    14
94371    14
94372    14
94373    14
94374    14
Name: Crop, Length: 94375, dtype: object

In [13]:
from sklearn.ensemble import RandomForestClassifier

Classifier = RandomForestClassifier(n_estimators=15, random_state=0)
Classifier.fit(X,y)

ValueError: Unknown label type: 'unknown'

In [ ]:
print(Classifier.score(X,y))

In [ ]:
predictionss=Classifier.predict([[1254.0,0]])
pred=format((predictionss[0]))

In [ ]:
pred

In [ ]:
import pickle

pickle.dump(Classifier,open('crop.pkl','wb'))

In [13]:
crop = pickle.load(open('crop.pkl', 'rb'))

NameError: name 'pickle' is not defined